version: "3.1"
name: cook-with-me-api
services:
  api:
    image: eclipse-temurin:21-jdk-alpine
    container_name: api
    volumes:
      - /tmp
      - ./target/CookWithMeApi-0.0.1-SNAPSHOT.jar:/app.jar
    entrypoint: ["java","-jar","/app.jar"]
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: psqlpassword

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8888:80"
